Test_CSharpCodeAtRunTime/Models/CodeAtRunTime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Test_CSharpCodeAtRunTime.Models
{
    public class CodeAtRunTime
    {
        public string parameters { get; set; }
        public string functionName { get; set; }
        public string source { get; set; }
        public string result { get; set; }
    }
}

Test_CSharpCodeAtRunTime/Controllers/CodeAtRunTimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test_CSharpCodeAtRunTime.Models;
using Test_CSharpCodeAtRunTime.Utilities;

namespace Test_CSharpCodeAtRunTime.Controllers
{
    public class CodeAtRunTimeController : Controller
    {
        private static CompileExecute _compileExecute = new CompileExecute();
        public CodeAtRunTime Rule = new CodeAtRunTime();
        // GET: CodeAtRunTime
        [ValidateInput(false)]
        public ActionResult Index()
        {
            Rule.functionName = "SayHello";
            Rule.source = @"public string SayHello()
        {
            return ""Hello World"";
        }";
            return View(Rule);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Run(CodeAtRunTime Rule)
        {
            object[] listaParams = null;
            int i = 0;
            var parameters = Rule.parameters.Split(',').ToList();
            if (parameters.Count > 0)
            {
                listaParams = new object[parameters.Count];
                foreach (var item in parameters)
                {
                    listaParams[i] = item;
                    i++;
                }
            }
            var Respuesta = _compileExecute.RunSomeCode(Rule.source, Rule.functionName, listaParams.ToArray());
            if (Respuesta.StatusCode == StatusResponse.OK)
            {
                Rule.result = Respuesta.Response;
            }
            else
            {
                foreach (var item in Respuesta.Errores)
                {
                    Rule.result += item.ToString();
                }
            }
            return View(Rule);
        }
    }
}

Test_CSharpCodeAtRunTime/Views/CodeAtRunTime/Index.cshtml
@model Test_CSharpCodeAtRunTime.Models.CodeAtRunTime

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Run", "CodeAtRunTime", FormMethod.Post, new { @class = "form-horizontal", role = "form" , ValidateRequestMode.Disabled }))
{
<div>
    <h4>CodeAtRunTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.functionName)
        </dt>
        
        <dd>
            @Html.EditorFor(model => model.functionName)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.parameters)
        </dt>

        <dd>
            @Html.EditorFor(model => model.parameters)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.source)
        </dt>

        <dd>
            @Html.TextAreaFor(model => model.source,new { cols = 100, rows = 20 })
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.result)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Run" class="btn btn-default" />
        </div>
    </div>
    
</p>
}

Test_CSharpCodeAtRunTime/Views/CodeAtRunTime/Run.cshtml
@model Test_CSharpCodeAtRunTime.Models.CodeAtRunTime

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <h4>CodeAtRunTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.functionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.functionName)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.parameters)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.parameters)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.source)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.source, new { cols = 100, rows = 20 })
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.result)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Back", "Index", Model)
</p>